name: Auto Update JP/SG Trojan (Weekly, Real Test)
on:
  schedule:
    - cron: '0 0 * * 0'  # æ¯å‘¨æ—¥åŒ—äº¬æ—¶é—´8ç‚¹è‡ªåŠ¨æ›´æ–°ï¼ˆä¸€å‘¨1æ¬¡ï¼‰
  workflow_dispatch:      # å…è®¸æ‰‹åŠ¨è§¦å‘æµ‹è¯•

jobs:
  update_jp_sg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}  # å¤ç”¨ä½ é…ç½®çš„PAT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyyaml requests urllib3
          sudo apt update && sudo apt install -y netcat-openbsd

      - name: Generate JP/SG Trojan (Real Speed Test)
        run: |
          cat > gen_jp_sg.py << 'EOF'
          import yaml
          import requests
          import base64
          import urllib3
          import subprocess
          import time
          from concurrent.futures import ThreadPoolExecutor, as_completed
          urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

          # ===================== æ ¸å¿ƒé…ç½® =====================
          MAX_WORKERS = 10  # å¹¶å‘æµ‹é€Ÿæ•°ï¼ˆå¹³è¡¡é€Ÿåº¦å’Œç¨³å®šæ€§ï¼‰
          MAX_DELAY = 150   # ä»…ä¿ç•™å»¶è¿Ÿ<150msçš„èŠ‚ç‚¹
          TIMEOUT = 10      # æ¯ä¸ªèŠ‚ç‚¹æµ‹é€Ÿè¶…æ—¶æ—¶é—´ï¼ˆç§’ï¼‰
          MAX_PROXIES = 50  # æ¯ä¸ªåœ°åŒºæœ€å¤šä¿ç•™50ä¸ªèŠ‚ç‚¹
          # ==================================================

          # 1. è¯»å–è®¢é˜…æºå¹¶æå–æ‰€æœ‰TrojanèŠ‚ç‚¹ï¼ˆåŽ»é‡ï¼‰
          with open('config.yaml', 'r', encoding='utf-8') as f:
              cfg = yaml.safe_load(f)
          subs = cfg['subs']
          all_trojan = []
          seen_nodes = set()  # æŒ‰æœåŠ¡å™¨+ç«¯å£+å¯†ç åŽ»é‡

          for url in subs:
              try:
                  r = requests.get(url, timeout=20, verify=False)
                  # å…¼å®¹Base64å’Œæ˜Žæ–‡è®¢é˜…
                  try:
                      txt = base64.b64decode(r.text).decode('utf-8', errors='ignore')
                  except:
                      txt = r.text
                  # è§£æžèŠ‚ç‚¹
                  data = yaml.safe_load(txt)
                  if 'proxies' in data:
                      for p in data['proxies']:
                          if p.get('type') == 'trojan':
                              server = p.get('server', '')
                              port = p.get('port', '')
                              password = p.get('password', '')
                              node_id = f"{server}:{port}:{password}"
                              if node_id not in seen_nodes:
                                  seen_nodes.add(node_id)
                                  all_trojan.append(p)
              except Exception as e:
                  print(f"å¤„ç†è®¢é˜…æº {url} å¤±è´¥: {e}")
                  continue

          print(f"âœ… æå–å¹¶åŽ»é‡åŽï¼Œå…± {len(all_trojan)} ä¸ªTrojanèŠ‚ç‚¹")

          # 2. çœŸå®žæµ‹é€Ÿå‡½æ•°ï¼ˆæµ‹è¯•ç«¯å£è¿žé€šæ€§+è®¡ç®—å»¶è¿Ÿï¼‰
          def test_trojan_delay(proxy):
              try:
                  server = proxy.get('server')
                  port = proxy.get('port')
                  if not server or not port:
                      return (proxy, float('inf'))
                  
                  # æµ‹è¯•ç«¯å£æ˜¯å¦å¼€æ”¾ï¼ˆæ ¸å¿ƒæµ‹é€Ÿé€»è¾‘ï¼‰
                  start_time = time.time()
                  nc_cmd = f"nc -zv -w {TIMEOUT} {server} {port}"
                  result = subprocess.run(
                      nc_cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE
                  )
                  if result.returncode != 0:
                      return (proxy, float('inf'))
                  
                  # è®¡ç®—å»¶è¿Ÿï¼ˆæ¯«ç§’ï¼‰
                  delay = round((time.time() - start_time) * 1000)
                  return (proxy, delay) if delay < MAX_DELAY else (proxy, float('inf'))
              except Exception as e:
                  return (proxy, float('inf'))

          # 3. å¹¶å‘æµ‹é€Ÿæ‰€æœ‰TrojanèŠ‚ç‚¹
          print(f"ðŸš€ å¼€å§‹å®žæµ‹èŠ‚ç‚¹å»¶è¿Ÿï¼ˆå¹¶å‘æ•°ï¼š{MAX_WORKERS}ï¼‰")
          valid_nodes = []
          with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
              futures = [executor.submit(test_trojan_delay, node) for node in all_trojan]
              for future in as_completed(futures):
                  proxy, delay = future.result()
                  if delay < MAX_DELAY:
                      proxy['delay'] = delay
                      valid_nodes.append(proxy)

          print(f"âœ… å®žæµ‹å®Œæˆï¼Œå…± {len(valid_nodes)} ä¸ªæœ‰æ•ˆTrojanèŠ‚ç‚¹")

          # 4. æŒ‰åœ°åŒºç­›é€‰å¹¶ç”Ÿæˆæ–‡ä»¶
          regions = {
              'jp': {
                  'keywords': ['æ—¥æœ¬', 'JP', 'jp'],
                  'file': 'sub_trojan_jp.yaml',
                  'name': 'æ—¥æœ¬'
              },
              'sg': {
                  'keywords': ['æ–°åŠ å¡', 'SG', 'sg'],
                  'file': 'sub_trojan_sg.yaml',
                  'name': 'æ–°åŠ å¡'
              }
          }

          for region, info in regions.items():
              # ç­›é€‰å¯¹åº”åœ°åŒºèŠ‚ç‚¹
              filtered_nodes = []
              for p in valid_nodes:
                  name = p.get('name', '').lower()
                  if any(kw in name or kw.lower() in name for kw in info['keywords']):
                      filtered_nodes.append(p)
              
              # æŒ‰å»¶è¿ŸæŽ’åºï¼Œå–å‰MAX_PROXIESä¸ª
              filtered_nodes.sort(key=lambda x: x.get('delay', MAX_DELAY))
              final_nodes = filtered_nodes[:MAX_PROXIES]
              
              # ç§»é™¤delayå±žæ€§ï¼Œç¬¦åˆClashæ ‡å‡†æ ¼å¼
              for node in final_nodes:
                  node.pop('delay', None)
              
              # æž„å»ºè®¢é˜…æ–‡ä»¶
              output_data = {
                  'proxies': final_nodes,
                  'proxy-groups': [{
                      'name': f'Auto-{region.upper()}-Trojan',
                      'type': 'url-test',
                      'proxies': [p['name'] for p in final_nodes],
                      'url': 'http://www.gstatic.com/generate_204',
                      'interval': 300
                  }]
              }
              
              # ä¿å­˜æ–‡ä»¶
              with open(info['file'], 'w', encoding='utf-8') as f:
                  yaml.dump(output_data, f, allow_unicode=True, sort_keys=False)
              print(f"âœ… ç”Ÿæˆ{info['name']}Trojanæ–‡ä»¶ï¼š{info['file']}ï¼Œä¿ç•™ {len(final_nodes)} ä¸ªä½Žå»¶è¿ŸèŠ‚ç‚¹")
          EOF

          # æ‰§è¡Œæµ‹é€Ÿç”Ÿæˆè„šæœ¬
          python gen_jp_sg.py

      - name: Commit JP/SG files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update JP/SG Trojan (weekly real speed test) ðŸ›¡ï¸"
          file_pattern: "sub_trojan_jp.yaml sub_trojan_sg.yaml"
          commit_options: "--allow-empty"  # å¼ºåˆ¶æäº¤ï¼Œä¿è¯æ—¶é—´åŒæ­¥
          push_options: "--force"
